[build]
  command = "curl -sL https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz | tar xz && mv zola*/zola /usr/local/bin/"
  publish = "public"


[build.environment]
ZOLA_VERSION = "0.19.2"